sirest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger_2/', include('trigger_2.urls')),
    path('trigger_3/', include('trigger_3.urls')),
    path('trigger-5/', include('trigger_5.urls')),
    path('trigger_6/', include('trigger_6.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('trigger-4/', include('trigger_4.urls')),
    path('login_page/', include('login_page.urls')),
]

trigger_5/urls.py
from django.urls import path
from . import views

app_name = 'trigger_5'

urlpatterns = [
    path('bahan-makanan/', views.show_bahan_makanan, name='show_bahan_makanan'),
    path('kategori-restoran/', views.show_kategori_restoran, name='show_kategori_restoran'),
    path('bahan-makanan-create/', views.create_bahan_makanan, name='create_bahan_makanan'),
    path('kategori-restoran-create/', views.create_kategori_restoran, name='create_kategori_restoran'),
    path('transaksi-pesanan-kurir/', views.show_transaksi_pesanan_kurir, name='show_transaksi_pesanan_kurir'),
    path('transaksi-pesanan-kurir-detail/<str:restoran>/<str:cabang>/<str:nama_pelanggan>/<str:waktu_pesanan>/<str:status_pesanan>', views.show_transaksi_pesanan_kurir_detail, name='show_transaksi_pesanan_kurir_detail'),
    path('kategori-restoran-delete/<str:id>', views.delete_kategori_restoran, name='delete_kategori_restoran'),
    path('bahan-makanan-delete/<str:id>', views.delete_bahan_makanan, name='delete_bahan_makanan'),
    path('transaksi-pesanan-kurir-update/<str:nama_pelanggan>/<str:waktu_pesanan>', views.update_transaksi_pesanan_kurir, name='update_transaksi_pesanan_kurir')
]

trigger_5/forms.py
from django import forms

class kategoriRestoranForm(forms.Form):

    name = forms.CharField(
        label = "Nama Kategori Restoran",
        max_length= 50,
        required= True,
        widget = forms.TextInput(attrs = {'class' : 'input', 'placeholder' : 'Name','class' : 'form-control'})
    )

class bahanMakananForm(forms.Form):

    name = forms.CharField(
        label = "Nama Bahan Makanan",
        max_length= 25,
        required= True,
        widget = forms.TextInput(attrs = {'class' : 'input', 'placeholder' : 'Name','class' : 'form-control'})
    )

trigger_5/views.py
from django.shortcuts import render, redirect
from .forms import bahanMakananForm, kategoriRestoranForm
from util.query import query
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse
from sirest.utils import get_role, is_authenticated
from datetime import datetime, timedelta
# Create your views here.
def show_bahan_makanan(request):
    if is_authenticated(request) == False:
        response = HttpResponseRedirect(reverse("login_page:login"))
        return response

    if is_authenticated(request) == False:
        response = HttpResponseRedirect(reverse("login_page:login"))
        return response

    role = get_role(request.session['email'], request.session['password'])
    if role == "courier":
        return redirect("../../dashboard/kurir/")
    elif role == "customer":
        return redirect("../../dashboard/pelanggan/")
    elif role == "restaurant":
        return redirect("../../dashboard/restoran/")

    data = {}
    bahan_makanan = query(f"""
    SELECT Id, Name
    FROM INGREDIENT 
    """)
    # cek referensi
    bahan_makanan_check = query("""
    SELECT Id
    FROM INGREDIENT I, FOOD_INGREDIENT FI
    WHERE Id = Ingredient
    """)
    # print(bahan_makanan_check)
    # print(bahan_makanan)
    list_bahan_makanan = []
    list_bahan_dependecies = [False]*len(bahan_makanan)
    for i in range(len(bahan_makanan_check)):
        idx = int(bahan_makanan_check[i][0][3:])-1
        if list_bahan_dependecies[idx] == False:
            list_bahan_dependecies[idx] = True
    for i in range(len(bahan_makanan)):
        list_bahan_makanan.append({
            'id' : bahan_makanan[i][0],
            'name' : bahan_makanan[i][1],
            'index' : i+1,
            'is_referenced' : list_bahan_dependecies[i] 
        })
    data['item_list'] = list_bahan_makanan
    print(data['item_list'])
    return render(request, 'bahan_makanan.html', data)

def create_bahan_makanan(request):
    if is_authenticated(request) == False:
        response = HttpResponseRedirect(reverse("login_page:login"))
        return response

    if is_authenticated(request) == False:
        response = HttpResponseRedirect(reverse("login_page:login"))
        return response

    role = get_role(request.session['email'], request.session['password'])
    if role == "courier":
        return redirect("../../dashboard/kurir/")
    elif role == "customer":
        return redirect("../../dashboard/pelanggan/")
    elif role == "restaurant":
        return redirect("../../dashboard/restoran/")

    role = get_role(request.session['email'], request.session['password'])
    if role == "courier":
        return redirect("../../dashboard/kurir/")
    elif role == "customer":
        return redirect("../../dashboard/pelanggan/")
    elif role == "restaurant":
        return redirect("../../dashboard/restoran/")
    
    form_gen = bahanMakananForm()
    if request.method == 'POST':
        form = bahanMakananForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name')
            rc_count = query(f"""
            SELECT COUNT(Id)
            FROM INGREDIENT
            """)
            id = 'ING' + str(rc_count)
            query(f"""
            INSERT INTO INGREDIENT
            VALUES ('{id}', '{name}')
            """)
            response = HttpResponseRedirect(reverse("trigger_5:show_bahan_makanan"))
            return response
    context = {
        'form' : form_gen
    }
    return render(request, 'bahan_makanan_create.html', context)

def show_kategori_restoran(request):
    if is_authenticated(request) == False:
        response = HttpResponseRedirect(reverse("login_page:login"))
        return response

    role = get_role(request.session['email'], request.session['password'])
    if role == "courier":
        return redirect("../../dashboard/kurir/")
    elif role == "customer":
        return redirect("../../dashboard/pelanggan/")
    elif role == "restaurant":
        return redirect("../../dashboard/restoran/")
    
    data = {}
    print(request.session['email'])
    kategori_restoran = query(f"""
    SELECT Id, Name
    FROM RESTAURANT_CATEGORY
    """)

    kategori_restoran_check = query("""
    SELECT Id
    FROM RESTAURANT_CATEGORY, RESTAURANT
    WHERE Id = RCategory
    """)

    list_restoran_dependecies = [False]*len(kategori_restoran)
    for i in range(len(kategori_restoran_check)):
        idx = int(kategori_restoran_check[i][0][2:])-1
        if list_restoran_dependecies[idx] == False:
            list_restoran_dependecies[idx] = True
    
    list_kategori_restoran = []
    for i in range(len(kategori_restoran)):
        list_kategori_restoran.append({
            'id' : kategori_restoran[i][0],
            'name' : kategori_restoran[i][1],
            'index' : i+1,
            'is_referenced' : list_restoran_dependecies[i]
        })

    

    data['item_list'] = list_kategori_restoran
    print(data['item_list'])
    return render(request, 'kategori_restoran.html', data)

def delete_bahan_makanan(request, id):
    print(id)
    query(f"""
    DELETE FROM INGREDIENT
    WHERE Id = '{id}'
    """)
    response = HttpResponseRedirect(reverse("trigger_5:show_bahan_makanan"))
    return response

def create_kategori_restoran(request):
    role = get_role(request.session['email'], request.session['password'])
    if role == "courier":
        return redirect("../../dashboard/kurir/")
    elif role == "customer":
        return redirect("../../dashboard/pelanggan/")
    elif role == "restaurant":
        return redirect("../../dashboard/restoran/")

    if request.method == 'POST':
        form = kategoriRestoranForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name')
            rc_count = query(f"""
            SELECT COUNT(Id)
            FROM RESTAURANT_CATEGORY
            """)
            id = 'RC' + str(rc_count)
            query(f"""
            INSERT INTO RESTAURANT_CATEGORY
            VALUES ('{id}', '{name}')
            """)
            response = HttpResponseRedirect(reverse("trigger_5:show_kategori_restoran"))
            return response
    form_gen = kategoriRestoranForm()
    context = {
        'form' : form_gen
    }
    return render(request, 'kategori_restoran_create.html', context)

def delete_kategori_restoran(request, id):
    print(id)
    query(f"""
    DELETE FROM RESTAURANT_CATEGORY
    WHERE Id = '{id}'
    """)
    response = HttpResponseRedirect(reverse("trigger_5:show_kategori_restoran"))
    return response

def show_transaksi_pesanan_kurir(request):
    if is_authenticated(request) == False:
        response = HttpResponseRedirect(reverse("login_page:login"))
    role = get_role(request.session['email'], request.session['password'])
    if role == "admin":
        return redirect("../../dashboard/admin/")
    elif role == "customer":
        return redirect("../../dashboard/pelanggan/")
    elif role == "restaurant":
        return redirect("../../dashboard/restoran/")
    
    quert_res = query(f"""
    SELECT Rname, Rbranch, Fname, Lname, T.Datetime, Name
    FROM TRANSACTION T, TRANSACTION_FOOD TF, USER_ACC U, TRANSACTION_HISTORY TH, TRANSACTION_STATUS TS
    WHERE CourierId = '{request.session['email']}' AND T.Email = TF.Email AND T.Datetime = TF.Datetime
    AND T.Email = U.Email AND T.Email = TH.Email AND T.Datetime = TH.Datetime AND TH.TSId = TS.Id
    """)
    # print (quert_res)
    # restoran_cabang = query(f"""
    # SELECT Rname, Rbranch
    # FROM TRANSACTION T, TRANSACTION_FOOD TF
    # WHERE CourierId = '{request.session['email']}' AND T.Email = TF.Email AND T.Datetime = TF.Datetime
    # """)

    # nama_pelanggan = query(f"""
    # SELECT Fname, Lname
    # FROM TRANSACTION T, USER_ACC U
    # WHERE T.Email = U.Email AND CourierId = '{request.session['email']}'
    # """)

    # waktu_pesanan = query(f"""
    # SELECT Datetime 
    # FROM TRANSACTION
    # WHERE CourierId = '{request.session['email']}'
    # """)

    # status_pesanan = query(f"""
    # SELECT Name
    # FROM TRANSACTION T, TRANSACTION_HISTORY TH, TRANSACTION_STATUS TS
    # WHERE T.Email = TH.Email AND T.Datetime = TH.Datetime AND TH.TSId = TS.Id AND CourierId = '{request.session['email']}'
    # """)
    # print(get_role(request.session['email'], '84jlaFTSs9'))
    # print(request.session['email'])
    # print(restoran_cabang)
    # print(nama_pelanggan)
    # print(waktu_pesanan)
    # print(status_pesanan)
    # print(len(quert_res))
    # print()
    # print(quert_res[0][0])
    item_list = []
    # print(type(waktu_pesanan[0][0]))
    # print(waktu_pesanan[0][0])
    for i in range(len(quert_res)):
        if(quert_res[i][5] == 'Delivering Order'):
            item_list.append({'restoran': quert_res[i][0],
                            'cabang' : quert_res[i][1],
                            'nama_pelanggan' : quert_res[i][2] + " " + quert_res[i][3],
                            'waktu_pesanan' : quert_res[i][4].strftime("%m-%d-%Y %H:%M:%S"),
                            'status_pesanan' : quert_res[i][5]}
                            )
    for i in range(len(item_list)):
        item_list[i]['index'] = i+1
    # data['restoran_cabang'] = restoran_cabang
    # data['nama_pelanggan'] = nama_pelanggan
    # data['waktu_pesanan'] = waktu_pesanan
    # data['status_pesanan'] = status_pesanan
    print(item_list)
    data = {}
    data = {'item_list' : item_list}
    print(data)

    return render(request, 'transaksi_pesanan_kurir.html', data)

def show_transaksi_pesanan_kurir_detail(request, restoran, cabang, nama_pelanggan, waktu_pesanan, status_pesanan):
    # print(restoran, cabang, nama_pelanggan, waktu_pesanan, status_pesanan)
    waktu_pesanan_min = datetime.strptime(waktu_pesanan, '%m-%d-%Y %H:%M:%S')
    print(waktu_pesanan_min)
    waktu_pesanan_max = waktu_pesanan_min + timedelta(seconds=1)
    fname, lname = nama_pelanggan.split()
    email = query(f"""

trigger_5/templates/bahan_makanan.html
{% extends 'base.html' %}


<html>

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}
{% block content %}

<style>
    body {
    background-color: #F8F9FC;
}
.container-md {
    background-color: #fff;
    border: 1px solid #CECACA;
    border-radius: 15px;
}

.back-btn {
    padding: 0;
    border: none;
    background: none;
}

.back-btn-div {
    margin-right: 25px;
}
</style>

  <head>
    <title>Bahan Makanan</title>
  </head>
  {% include 'navbar_admin.html' %}

<div style="height:100px;"></div>
<div class="container-sm">
    <div class="table-responsive-md">
        <table class="table table-hover rounded rounded-3 overflow-hidden">
            <thead class="table" style="background-color: #2D55D0; color: #fff;">
                <tr>
                    <th class="text-center" style="padding: 1rem 1rem;">No</th>
                    <th class="text-center" style="padding: 1rem 1rem;">Nama Bahan Makanan</th>
                    <th class="text-center" style="padding: 1rem 1rem;">Aksi</th>
                </tr>
            </thead>
            <tbody id ="report_table" >
                {% for item in item_list %}
                <tr style="cursor: pointer;">
                    <td class="text-center">{{item.index}}</td>
                    <td class="text-center">{{item.name}}</td>
                    {% if item.is_referenced %}      
                        <td></td>
                    {% else %}
                        <td class="text-center"><a class="btn btn-dark" href="{% url 'trigger_5:delete_bahan_makanan' item.id %}">Hapus</a></td>
                    {% endif %} 
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>  

</html>

{% endblock %}

trigger_5/templates/bahan_makanan_create.html
{% extends 'base.html' %}


<html>

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}
{% block content %}
{% include 'navbar_admin.html' %}
<h>FORM BUAT BAHAN MAKANAN</h>

<form method="POST" id = "form">
    {% csrf_token %}
    {{form.as_p}}
    <button id="SubmitButton" type="submit" class="btn btn-primary" data-bs-dismiss="modal">Simpan</button>
</form>

{% endblock %}

trigger_5/templates/kategori_restoran.html
{% extends 'base.html' %}


<html>

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}
{% block content %}

<style>
    body {
    background-color: #F8F9FC;
}
.container-md {
    background-color: #fff;
    border: 1px solid #CECACA;
    border-radius: 15px;
}

.back-btn {
    padding: 0;
    border: none;
    background: none;
}

.back-btn-div {
    margin-right: 25px;
}
</style>

  <head>
    <title>Kategori Restoran</title>
  </head>
    
  {% include 'navbar_admin.html' %}
<div style="height:100px;"></div>
<div class="container-sm">
    <div class="table-responsive-md">
        <table class="table table-hover rounded rounded-3 overflow-hidden">
            <thead class="table" style="background-color: #2D55D0; color: #fff;">
                <tr>
                    <th class="text-center" style="padding: 1rem 1rem;">No</th>
                    <th class="text-center" style="padding: 1rem 1rem;">Kategori Restoran</th>
                    <th class="text-center" style="padding: 1rem 1rem;">Aksi</th>
                </tr>
                
            </thead>
            <tbody id ="report_table" >
                {% for item in item_list %}
                <tr style="cursor: pointer;">
                    <td class="text-center">{{item.index}}</td>
                    <td class="text-center">{{item.name}}</td>
                    {% if item.is_referenced %}      
                        <td></td>
                    {% else %}
                        <td class="text-center"><a class="btn btn-dark" href="{% url 'trigger_5:delete_kategori_restoran' item.id %}">Hapus</a></td>
                    {% endif %} 
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>  

</html>

{% endblock %}

trigger_5/templates/kategori_restoran_create.html
{% extends 'base.html' %}


<html>

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}
{% block content %}

{% include 'navbar_admin.html' %}
<h style="text-align:center">FORM BUAT KATEGORI RESTORAN</h>

<form method="POST" id = "form">
    {% csrf_token %}
    {{form.as_p}}
    <button id="SubmitButton" type="submit" class="btn btn-primary" data-bs-dismiss="modal">Simpan</button>
</form>

{% endblock %}

trigger_5/templates/transaksi_pesanan_kurir.html
{% extends 'base.html' %}


<html>

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}
{% block content %}

<style>
    body {
    background-color: #F8F9FC;
}
.container-md {
    background-color: #fff;
    border: 1px solid #CECACA;
    border-radius: 15px;
}

.back-btn {
    padding: 0;
    border: none;
    background: none;
}

.back-btn-div {
    margin-right: 25px;
}
</style>

  <head>
    <title>Kategori Restoran</title>
  </head>
    
{% include 'navbar_kurir.html' %}
<div style="height:100px;"></div>
<div class="container-sm">
    <div class="table-responsive-md">
        <table class="table table-hover rounded rounded-3 overflow-hidden">
            <thead class="table" style="background-color: #2D55D0; color: #fff;">
                <tr>
                    <th class="text-center" style="padding: 1rem 1rem;">No</th>
                    <th class="text-center" style="padding: 1rem 1rem;">Restoran - Cabang</th>
                    <th class="text-center" style="padding: 1rem 1rem;">Nama Pelanggan</th>
                    <th class="text-center" style="padding: 1rem 1rem;">Waktu Pesanan Dibuat</th>
                    <th class="text-center" style="padding: 1rem 1rem;">Status Pesanan</th>
                    <th class="text-center" style="padding: 1rem 1rem;">Aksi</th>
                </tr>
                
            </thead>
            <tbody id ="report_table" >
                {% for item in item_list %}
                <tr style="cursor: pointer;">
                    <td class="text-center">{{item.index}}</td>
                    <td class="text-center">{{item.restoran}} {{item.cabang}}</td>
                    <td class="text-center">{{item.nama_pelanggan}}</td>
                    <td class="text-center">{{item.waktu_pesanan}}</td>
                    <td class="text-center">{{item.status_pesanan}}</td>
                    <td class="text-center"><a class="btn btn-secondary" href="{% url 'trigger_5:show_transaksi_pesanan_kurir_detail' item.restoran item.cabang item.nama_pelanggan item.waktu_pesanan item.status_pesanan%}">Detail</a>
                    <a class="btn btn-secondary" href="{% url 'trigger_5:update_transaksi_pesanan_kurir' item.nama_pelanggan item.waktu_pesanan%}">Selesai</a> </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>  

</html>

{% endblock %}

trigger_5/templates/transaksi_pesanan_kurir_detail.html
{% extends 'base.html' %}


<html>

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}
{% block content %}
{% include 'navbar_kurir.html' %}
<h>Ringkasan Pesanan</h>

<p> Waktu Pemesanan: 2022-11-04 11:30:05 <br><br>

Nama Pelanggan: {{nama_pelanggan}} <br>
Jalan: {{transaksi.street}} <br>
Kecamatan: {{transaksi.district}} <br>
Kota: {{transaksi.city}} <br>
Provinsi: {{transaksi.province}} <br><br>

Restoran: {{restoran_detail.rname}} {{restoran_detail.rbranch}}<br>
Jalan: {{restoran_detail.street}} <br>
Kecamatan: {{restoran_detail.district}} <br>
Kota: {{restoran_detail.city}} <br>
Provinsi: {{restoran_detail.province}} <br><br>

Makanan yang dipesan: <br>
{% for item in makanan %}
    {{item.index}}. {{item.foodname}}
    {% if item.note != null%} 
        - item.note 
    {% else %}
    {% endif %} <br>
{% endfor %}
Total Harga Makanan: {{transaksi.totalfood}} <br>
Total Diskon: {{transaksi.totaldiscount}} <br>
Biaya Pengantaran: {{transaksi.deliveryfee}} <br>
Total Biaya: {{transaksi.totalprice}} <br>
Jenis Pembayaran: {{jenis_pembayaran.name}} <br><br>

Status Pembayaran: {{status_pembayaran.name}} <br>
Status Pesanan: {{status_pesanan}} <br><br>

Kurir: {{kurir.fname}} {{kurir.lname}} <br>
Plat Kendaraan: {{kurir.platenum}} <br>
Jenis Kendaraan: {{kurir.vehicletype}} <br>
Merk Kendaraan: {{kurir.vehiclebrand}} <br>

</p>

<a class="btn btn-secondary" href="{% url 'trigger_5:show_transaksi_pesanan_kurir' %}">Kembali</a></td>
{% endblock %}