dashboard/urls.py
from django.urls import path
from dashboard.views import dashboard_kurir, dashboard_pelanggan, dashboard_restoran, dashboard_admin, detail_kurir, detail_pelanggan, detail_restoran

app_name = "dashboard"

urlpatterns = [
    path("admin/", dashboard_admin, name = "dashboard_admin"),
    path("pelanggan/", dashboard_pelanggan, name = "dashboard_pelanggan"),
    path("restoran/", dashboard_restoran, name = "dashboard_resto"),
    path("kurir/", dashboard_kurir, name = "dashboard_kurir"),
    path("detail/pelanggan/<str:email>/", detail_pelanggan, name = "detail_pelanggan"),
    path("detail/restoran/<str:email>/", detail_restoran, name = "detail_resto"),
    path("detail/kurir/<str:email>/", detail_kurir, name = "detail_kurir"),
]

sirest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger_2/', include('trigger_2.urls')),
    path('trigger_3/', include('trigger_3.urls')),
    path('trigger-5/', include('trigger_5.urls')),
    path('trigger_6/', include('trigger_6.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('trigger-4/', include('trigger_4.urls')),
    path('login_page/', include('login_page.urls')),
]

trigger_2/urls.py
from django.urls import path
from .views import create_jam_operasional, delete_jam_operasional, detail_transaksi_pesanan_restoran, read_jam_operasional, read_resto_pay, isi_resto_pay, read_transaksi_pesanan_restoran, tarik_resto_pay, update_jam_operasional, update_transaksi_pesanan_restoran

app_name = "trigger_2"

urlpatterns = [
    path("restopay/read/", read_resto_pay, name = "read_resto_pay"),
    path("restopay/isi/", isi_resto_pay, name = "isi_resto_pay"),
    path("restopay/tarik/", tarik_resto_pay, name = "tarik_resto_pay"),
    
    path("transaksipesanan/restoran/read/", read_transaksi_pesanan_restoran, name = "read_transaksi_pesanan_restoran"),
    path("transaksipesanan/restoran/update/<str:email>/<str:datetime>/<str:status_id>/", update_transaksi_pesanan_restoran, name = "update_transaksi_pesanan_restoran"),
    path("transaksipesanan/restoran/detail/<str:email>/<str:datetime>/", detail_transaksi_pesanan_restoran, name = "detail_transaksi_pesanan_restoran"),

    path("jamoperasional/create/", create_jam_operasional, name = "create_jam_operasional"),
    path("jamoperasional/read/", read_jam_operasional, name = "read_jam_operasional"),
    path("jamoperasional/update/<str:day>/", update_jam_operasional, name = "update_jam_operasional"),
    path("jamoperasional/delete/<str:day>/", delete_jam_operasional, name = "delete_jam_operasional"),
]

trigger_4/urls.py
from django.urls import path
from . import views

app_name = 'trigger_4'

urlpatterns = [
    # Kategori Makanan
    path('form-kategori-makanan/', views.create_kategori_makanan, name='form-kategori-makanan'),
    path('list-kategori-makanan/', views.read_kategori_makanan, name='list-kategori-makanan'),
    path('hapus-kategori-makanan/<str:id>/', views.delete_kategori_makanan, name='hapus-kategori-makanan'),
    
    # Pesan Makanan (POV Pelanggan)
    path('form-alamat-pesanan/', views.create_alamat_pesanan, name='form-alamat-pesanan'),
    path('list-resto/<str:province>/', views.pilih_restolist_pesanan, name='list-resto'),
    path('list-menu/<str:rname>/<str:rbranch>/', views.pilih_restomenu_pesanan, name='list-menu'),
    path('list-pesanan/', views.list_pesanan, name='list-pesanan'),
    path('konfirmasi-pembayaran/', views.konfirmasi_pembayaran, name='konfirmasi-pembayaran'),
    path('detail-pesanan/<str:current_date>/', views.detail_pesanan, name='detail-pesanan'),
    path('daftar-pesanan/', views.daftar_pesanan, name='daftar-pesanan'),
]

trigger_5/urls.py
from django.urls import path
from . import views

app_name = 'trigger_5'

urlpatterns = [
    path('bahan-makanan/', views.show_bahan_makanan, name='show_bahan_makanan'),
    path('kategori-restoran/', views.show_kategori_restoran, name='show_kategori_restoran'),
    path('bahan-makanan-create/', views.create_bahan_makanan, name='create_bahan_makanan'),
    path('kategori-restoran-create/', views.create_kategori_restoran, name='create_kategori_restoran'),
    path('transaksi-pesanan-kurir/', views.show_transaksi_pesanan_kurir, name='show_transaksi_pesanan_kurir'),
    path('transaksi-pesanan-kurir-detail/<str:restoran>/<str:cabang>/<str:nama_pelanggan>/<str:waktu_pesanan>/<str:status_pesanan>', views.show_transaksi_pesanan_kurir_detail, name='show_transaksi_pesanan_kurir_detail'),
    path('kategori-restoran-delete/<str:id>', views.delete_kategori_restoran, name='delete_kategori_restoran'),
    path('bahan-makanan-delete/<str:id>', views.delete_bahan_makanan, name='delete_bahan_makanan'),
    path('transaksi-pesanan-kurir-update/<str:nama_pelanggan>/<str:waktu_pesanan>', views.update_transaksi_pesanan_kurir, name='update_transaksi_pesanan_kurir')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% block meta %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
  {% endblock meta %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
  {% block content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  
  {% endblock content %}
</body>

</html>

templates/navbar_admin.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light px-5">
        <a class="navbar-brand" href="{% url 'dashboard:dashboard_admin' %}">Dashboard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Restoran
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'trigger_5:show_kategori_restoran' %}">Daftar Kategori Restoran</a>
                  <a class="dropdown-item" href="{% url 'trigger_5:create_kategori_restoran' %}">Buat Kategori Restoran</a>
                  <a class="dropdown-item" href="{% url 'trigger_4:list-kategori-makanan' %}">Daftar Kategori Makanan</a>
                  <a class="dropdown-item" href="{% url 'trigger_4:form-kategori-makanan' %}">Buat Kategori Makanan</a>
                  <a class="dropdown-item" href="{% url 'trigger_5:show_bahan_makanan' %}">Daftar Bahan Makanan</a>
                  <a class="dropdown-item" href="{% url 'trigger_5:create_bahan_makanan' %}">Buat Bahan Makanan</a>
                  <a class="dropdown-item" href="#">Daftar Restoran dan Makanan</a>
                </div>
              </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Promo
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Daftar Promo</a>
                  <a class="dropdown-item" href="#">Buat Promo</a>
                </div>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Pesanan
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Daftar Tarik Pengiriman per KM</a>
                <a class="dropdown-item" href="#">Buat Tarik Pengiriman per KM</a>
              </div>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'login_page:logout' %}"><span class="sr-only">Logout</span></a>
            </li>
          </ul>
        </div>
      </nav>
</body>

templates/navbar_kurir.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light px-5">
        <a class="navbar-brand" href="{% url 'dashboard:dashboard_kurir' %}">Dashboard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#"><span class="sr-only">Daftar Restoran dan Makanan</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pesanan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'trigger_5:show_transaksi_pesanan_kurir' %}">Pesanan Berlangsung</a>
                  <a class="dropdown-item" href="#">Riwayat Pesanan</a>
                </div>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'trigger_2:read_resto_pay' %}"><span class="sr-only">RestoPay</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'login_page:logout' %}"><span class="sr-only">Logout</span></a>
            </li>
          </ul>
        </div>
      </nav>
</body>

templates/navbar_pelanggan.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light px-5">
        <a class="navbar-brand" href="{% url 'dashboard:dashboard_pelanggan' %}">Dashboard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#"><span class="sr-only">Daftar Restoran dan Makanan</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Pesanan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'trigger_4:form-alamat-pesanan' %}">Buat Pesanan</a>
                  <a class="dropdown-item" href="{% url 'trigger_4:daftar-pesanan' %}">Pesanan Berlangsung</a>
                  <a class="dropdown-item" href="{% url 'trigger_4:daftar-pesanan' %}">Riwayat Pesanan</a>
                </div>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'trigger_2:read_resto_pay' %}"><span class="sr-only">RestoPay</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'login_page:logout' %}"><span class="sr-only">Logout</span></a>
            </li>
          </ul>
        </div>
      </nav>
</body>

templates/navbar_restoran.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light px-5">
        <a class="navbar-brand" href="{% url 'dashboard:dashboard_resto' %}">Dashboard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Jam Operasional
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'trigger_2:read_jam_operasional' %}">Daftar Jam Operasional</a>
                  <a class="dropdown-item" href="{% url 'trigger_2:create_jam_operasional' %}">Buat Jam Operasional</a>
                </div>
              </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Makanan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Daftar Makanan</a>
                  <a class="dropdown-item" href="#">Buat Makanan</a>
                </div>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Pesanan
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'trigger_2:read_transaksi_pesanan_restoran' %}">Pesanan Berlangsung</a>
                <a class="dropdown-item" href="#">Riwayat Pesanan</a>
              </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Promo
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Daftar Promo Tersedia</a>
                  <a class="dropdown-item" href="#">Daftar Promo Restoran</a>
                </div>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'trigger_2:read_resto_pay' %}"><span class="sr-only">RestoPay</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'login_page:logout' %}"><span class="sr-only">Logout</span></a>
            </li>
          </ul>
        </div>
      </nav>
</body>