sirest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger_2/', include('trigger_2.urls')),
    path('trigger_3/', include('trigger_3.urls')),
    path('trigger-5/', include('trigger_5.urls')),
    path('trigger_6/', include('trigger_6.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('trigger-4/', include('trigger_4.urls')),
    path('login_page/', include('login_page.urls')),
]

trigger_4/urls.py
from django.urls import path
from . import views

app_name = 'trigger_4'

urlpatterns = [
    # Kategori Makanan
    path('form-kategori-makanan/', views.create_kategori_makanan, name='form-kategori-makanan'),
    path('list-kategori-makanan/', views.read_kategori_makanan, name='list-kategori-makanan'),
    path('hapus-kategori-makanan/<str:id>/', views.delete_kategori_makanan, name='hapus-kategori-makanan'),
    
    # Pesan Makanan (POV Pelanggan)
    path('form-alamat-pesanan/', views.create_alamat_pesanan, name='form-alamat-pesanan'),
    path('list-resto/<str:province>/', views.pilih_restolist_pesanan, name='list-resto'),
    path('list-menu/<str:rname>/<str:rbranch>/', views.pilih_restomenu_pesanan, name='list-menu'),
    path('list-pesanan/', views.list_pesanan, name='list-pesanan'),
    path('konfirmasi-pembayaran/', views.konfirmasi_pembayaran, name='konfirmasi-pembayaran'),
    path('detail-pesanan/<str:current_date>/', views.detail_pesanan, name='detail-pesanan'),
    path('daftar-pesanan/', views.daftar_pesanan, name='daftar-pesanan'),
]

trigger_4/models.py
from django.db import models

# Create your models here.

trigger_4/forms.py
from django import forms

class kategoriMakananForm(forms.Form):

    name = forms.CharField(
        label = "Nama Kategori Makanan",
        max_length= 50,
        required= True,
        widget = forms.TextInput(attrs = {'class' : 'input', 'placeholder' : 'Name','class' : 'form-control'})
    )

PROVINCE = ['DKI Jakarta', 'Banten', 'Jawa Barat', 'Jawa Tengah', 'Jawa Timur',
            'Bali', 'DI Yogyakarta', 'Kalimantan Utara', 'Kalimantan Barat', 'Riau']

class pengisianAlamatPesananMakananForm(forms.Form):
        jalan = forms.CharField(
        label = "Jalan",
        max_length= 50,
        required= True,
        widget = forms.TextInput(attrs = {'class' : 'input', 'placeholder' : 'Name','class' : 'form-control'})
    )
        kecamatan = forms.CharField(
        label = "Kecamatan",
        max_length= 50,
        required= True,
        widget = forms.TextInput(attrs = {'class' : 'input', 'placeholder' : 'Name','class' : 'form-control'})
    )
        kota = forms.CharField(
        label = "Kota",
        max_length= 50,
        required= True,
        widget = forms.TextInput(attrs = {'class' : 'input', 'placeholder' : 'Name','class' : 'form-control'})
    )
        provinsi = forms.CharField(
            label = "Provinsi",
            widget = forms.Select(choices=PROVINCE)
    )

trigger_4/views.py
from json import tool
from django.shortcuts import render, redirect
from django.contrib import messages
from util.query import *
from datetime import datetime as date


from login_page.views import get_session_data

# Create your views here.

# CR Kategori Makanan
def create_kategori_makanan(request):

    if request.method != "POST":
        return render(request, 'kategori_makanan_form.html')
    
    nama_kategori = request.POST['name']
    id_kategori = ""

    # Menentukan ID
    max_id_get = query("SELECT MAX(id) FROM food_category;")
    max_id = max_id_get[0][0][-2:]
    id_kategori = "FC" + str(int(max_id) + 1).zfill(2);

    query(
        f"""
        INSERT INTO food_category VALUES ('{id_kategori}', '{nama_kategori}');
    """)

    return redirect('/trigger-4/list-kategori-makanan/')
    

def delete_kategori_makanan(request, id): 
    query(f"""
        DELETE FROM food_category 
        WHERE id = '{id}';
    """)

    return redirect('/trigger-4/list-kategori-makanan/')

def read_kategori_makanan(request):
    data = get_session_data(request)

    data['kategori_makanan'] = query("""
        SELECT * FROM food_category;
    """)

    return render(request, 'kategori_makanan_list.html', data)

# CR Transaksi Pelanggan Alamat
def create_alamat_pesanan(request):
    data = get_session_data(request)

    province_list = query("""
        SELECT province FROM delivery_fee_per_km;
    """)
    data['province_list'] = province_list

    if request.method != "POST":
        return render(request, 'tpel_alamat_form.html', data)

    street = request.POST['street']
    district = request.POST['district']
    city = request.POST['city']
    province = request.POST['province']

    response = redirect('/trigger-4/list-resto/' + province + '/')

    response.set_cookie('street', street)
    response.set_cookie('district', district)
    response.set_cookie('city', city)
    response.set_cookie('province', province)
    return response


def pilih_restolist_pesanan(request, province):
    data = get_session_data(request)

    restaurant_list = query(f"""
        SELECT rname, rbranch
        FROM restaurant
        WHERE province = '{province}';
    """)
    promo_list = query(f"""
        SELECT rp.rname, rp.rbranch, p.promoname
        FROM restaurant_promo rp 
            INNER JOIN promo p ON rp.pid = p.id
    """)
    data['restaurant_list'] = restaurant_list
    data['promo_list'] = promo_list

    return render(request, 'tpel_choose_restolist_form.html', data)


def pilih_restomenu_pesanan(request, rname, rbranch):
    data = get_session_data(request)
    email = str(request.session["email"]).strip()
    current_date = str(date.now())[:23]
    
    menu_list = query(f"""
        SELECT foodname, price
        FROM food
        WHERE rname = '{rname}' AND rbranch = '{rbranch}';
    """)
    payment_list = query(f"""
        SELECT name
        FROM payment_method;
    """)

    data['menu_list'] = menu_list
    data['payment_list'] = payment_list
    menu_count = len(menu_list)

    if request.method != "POST":
        return render(request, 'tpel_choose_restomenu_form.html', data)

    # AFTER POST
    vehicle = request.POST['vehicle']
    payment = request.POST['payment']

    street = request.COOKIES.get('street')
    district = request.COOKIES.get('district')
    city = request.COOKIES.get('city')
    province = request.COOKIES.get('province')
    
    total_food = 0
    amount_food = 0

    for i in range(menu_count):
        menu_qty = int(request.POST['jumlah-' + str(i+1)])
        if menu_qty > 0:
            amount_food += menu_qty
            total_food += menu_qty * menu_list[i][1]
        else:
            continue
    
    if amount_food == 0:
        messages.warning(request, "Silahkan pilih menu terlebih dahulu!")
        return redirect('/trigger-4/list-menu/' + rname + '/' + rbranch + '/')

    diskon_mt = query(f"""
        SELECT SUM(p.discount)
        FROM restaurant_promo rp INNER JOIN promo p on rp.pid = p.id INNER JOIN min_transaction_promo mtp on p.id = mtp.id
        WHERE rname = '{rname}' AND rbranch = '{rbranch}' AND mtp.minimumtransactionnum <= {total_food};
    """)

    diskon_sp = query(f"""
        SELECT SUM(p.discount)
        FROM restaurant_promo rp INNER JOIN promo p on rp.pid = p.id INNER JOIN special_day_promo sdp on p.id = sdp.id
        WHERE rname = '{rname}' AND rbranch = '{rbranch}';
    """)


    if diskon_mt[0][0] == None and diskon_sp[0][0] == None:
        total_diskon = 0
    elif diskon_mt[0][0] == None:
        total_diskon = int(diskon_sp[0][0])
    elif diskon_sp[0][0] == None:
        total_diskon = int(diskon_mt[0][0])
    else:
        total_diskon = int(diskon_mt[0][0]) + int(diskon_sp[0][0])

    diskon_value = total_food * total_diskon / 100

    pmid = ""
    if payment == "RestoPay":
        pmid = "PM01"
    elif payment == "Other e-Wallet":
        pmid = "PM02"
    elif payment == "Bank Transfer":
        pmid = "PM03"
    elif payment == "RestoPay Paylater":
        pmid = "PM04"
    else:
        pmid = "PM05"

    check_txi_post = query(f"""
        INSERT INTO transaction VALUES (
            '{email}', '{current_date}', '{street}', '{district}', '{city}', '{province}', 
            '{total_food}', '{diskon_value}', '{0}', '{0}', '{0}', '{pmid}', '{'PS01'}', '{'DF01'}', '{'vwixonb@sfgate.com'}');
        """)
    
    print(check_txi_post)

    for i in range(menu_count):

        menu_qty = int(request.POST['jumlah-' + str(i+1)])
        if menu_qty > 0:
            menu_name = menu_list[i][0] 
            menu_note = request.POST['catatan-' + str(i+1)]
            check_menu_post = query(f"""
                INSERT INTO transaction_food VALUES (
                    '{email}', '{current_date}', '{rname}', '{rbranch}', '{menu_name}', {menu_qty}, '{menu_note}'
                );
            """)
            print(check_menu_post)
        else:
            continue

    response = redirect('/trigger-4/list-pesanan/')
    response.set_cookie('current_date', current_date)
    response.set_cookie('vehicle', vehicle)
    response.set_cookie('payment', payment)

    return response

def list_pesanan(request):
    data = get_session_data(request)
    email = str(request.session["email"]).strip()
    
    current_date = request.COOKIES.get('current_date')
    data['current_date'] = current_date

    data['transaction'] = query(f"""
        SELECT *
        FROM transaction t
        WHERE t.email = '{email}' AND t.datetime = '{current_date}';
    """)

    data['order'] = query(f"""
        SELECT tf.foodname, f.price, tf.amount, tf.amount*f.price AS subtotal
        FROM transaction_food tf
        INNER JOIN food f ON tf.foodname = f.foodname AND tf.rname = f.rname AND tf.rbranch = f.rbranch
        WHERE tf.email = '{email}' AND tf.datetime = '{current_date}';
    """)

    print(data['transaction'])
    print(data['order'])
    
    data['total_harga'] = data['transaction'][0][6]
    data['vehicle'] = request.COOKIES.get('vehicle')
    data['payment'] = request.COOKIES.get('payment')
    data['total_diskon'] = data['transaction'][0][7]
    data['biaya_pengantaran'] = data['transaction'][0][8]
    data['total_biaya'] = data['transaction'][0][9]

    if request.method != "POST":
        return render(request, 'tpel_pesanan_list.html', data)

    return redirect('/trigger-4/konfirmasi-pembayaran/')

def konfirmasi_pembayaran(request):
    data = get_session_data(request)
    email = str(request.session["email"]).strip()
    status_date = str(date.now())[:23]
    
    current_date = request.COOKIES.get('current_date')
    data['waktu_pemesanan'] = current_date

    # NAMA PELANGGAN
    data['nama_pelanggan'] = query(f"""
        SELECT CONCAT(fname, ' ', lname)
        FROM user_acc
        WHERE email = '{email}';
    """)[0][0]

    print(data['nama_pelanggan'])

    transaction = query(f"""
        SELECT *
        FROM transaction t
        WHERE t.email = '{email}' AND t.datetime = '{current_date}';
    """)

    print(transaction)
    
    transaction_status = query(f"""
        INSERT INTO transaction_history VALUES (
            '{email}', '{current_date}', '{'TS01'}', '{status_date}'
        );
    """)

    data['pel_jalan'] = transaction[0][2]
    data['pel_kecamatan'] = transaction[0][3]
    data['pel_kota'] = transaction[0][4]
    data['pel_provinsi'] = transaction[0][5]


    data['order'] = query(f"""
        SELECT tf.foodname, f.price, tf.amount, tf.amount*f.price AS subtotal, tf.note, tf.rname, tf.rbranch
        FROM transaction_food tf
        INNER JOIN food f ON tf.foodname = f.foodname AND tf.rname = f.rname AND tf.rbranch = f.rbranch
        WHERE tf.email = '{email}' AND tf.datetime = '{current_date}';
    """)

    print(data['order'])

    rname = data['order'][0][5]
    rbranch = data['order'][0][6]

    restoran = query(f"""
        SELECT CONCAT(rname, ' ', rbranch) AS restoran, street, district, city, province 
        FROM restaurant
        WHERE rname = '{rname}' AND rbranch = '{rbranch}';
    """)

    print(restoran)

    data['restoran'] = restoran[0][0]
    data['rest_jalan'] = restoran[0][1]
    data['rest_kecamatan'] = restoran[0][2]
    data['rest_kota'] = restoran[0][3]
    data['rest_provinsi'] = restoran[0][4]
    
    data['total_harga_makanan'] = transaction[0][6]
    data['total_diskon'] = transaction[0][7]
    data['biaya_pengantaran'] = transaction[0][8]
    data['total_biaya'] = transaction[0][9]
    data['payment'] = request.COOKIES.get('payment')


    if request.method != "POST":
        return render(request, 'tpel_pesanan_pay.html', data)

    query(f"""
        UPDATE transaction
        SET psid = 'PS02'
        WHERE email = '{email}' AND datetime = '{current_date}';
        """)

    return redirect('/trigger-4/detail-pesanan/' + str(current_date) + '/')

def detail_pesanan(request, current_date):
    data = get_session_data(request)

trigger_4/templates/kategori_makanan_form.html
{% extends 'base.html' %}

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}

{% block content %}

{% include 'navbar_admin.html' %}
<div class="d-flex flex-row justify-content-center">
    <div class="d-flex flex-column align-items-center"> 
        <form method="post">
            {% csrf_token %}
            <h2 class="lead pt-4 pb-3">FORM BUAT KATEGORI MAKANAN</h1>
            <!-- cards -->
            <div class="card d-flex flex-column align-items-center" style="width: 900px;">
                
                <div class="d-flex flex-row justify-content-between p-3 align-items-center" style="width: 100%;"> 
                    <label for="name" class="fs-6 text-wrap fw-normal" style="width: 60%;">Nama Kategori Makanan</label>
                    <input type="text" id="name" name="name" placeholder="Kategori Baru" class="form-control" style="width: 40%;" required>
                </div>
            </div>
            
            <div class="pt-3"></div>
            <button type="submit" class="btn btn-dark">Simpan</button>
        </form>
    </div>
</div>

{% endblock content %}

trigger_4/templates/kategori_makanan_list.html
{% extends 'base.html' %}

{% block meta %}

{% endblock meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% block content %}

{% include 'navbar_admin.html' %}
<div class="d-flex flex-row justify-content-center ">
    <div class="d-flex flex-column align-items-center">
        
        <h2 class="lead pt-4 pb-3">KATEGORI MAKANAN LIST</h1>
        
        

        <!-- cards -->
        <div class="card" style="width: 900px;">

            <div class="px-2 py-3 border-dark d-flex flex-row align-items-center" style="width: 100%;">
              <div class="d-flex flex-column align-items-center px-2 fs-6 text-wrap fw-normal" 
              style="width: 5%;">No</div>
              
              <div class="d-flex flex-column align-items-start px-2 fs-6 text-wrap fw-normal" 
              style="width: 75%;">Nama Kategori Makanan</div>
              
              <div class="d-flex flex-column align-items-start px-2 fs-6 text-wrap fw-normal" 
              style="width: 20%;">Aksi</div>
            </div>

            
            {% for k in kategori_makanan %}
            <div class="px-2 border-dark d-flex flex-row align-items-center" style="width: 100%;">
              <div class="d-flex flex-column align-items-end px-2 fs-6 text-wrap fw-normal" 
              style="width: 5%;">{{ forloop.counter }}</div>
              
              <div class="d-flex flex-column align-items-start px-2 fs-6 text-wrap fw-normal" 
              style="width: 75%;">{{ k.name }}</div>

              <div style="width: 20%;">
                <a href="{% url 'trigger_4:hapus-kategori-makanan' id=k.id %}" type="submit" class="btn btn-sm btn-danger">Hapus</a>
              </div>

            </div>
            <div class="d-flex flex-row py-1">
            </div>
            {% endfor %}

            <div class="pt-3"></div>        
            
        </div>

    </div>
</div>

{% endblock content %}

trigger_4/templates/pesanan_berlangsung.html
{% extends 'base.html' %}

{% block meta %}

<style>

    div {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

</style>

{% endblock meta %}

{% block content %}

<div class="row">
    <div class="col">
        <h2 class=" pt-4 pb-3"><strong>Pesanan Berlangsung</strong></h2>
    </div>
</div>

<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">No</th>
        <th scope="col">Restoran</th>
        <th scope="col">Waktu Pesanan Dibuat</th>
        <th scope="col">Status Pesanan</th>
        <th scope="col">Aksi</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>Warung Mantap Depok</td>
        <td>2022-11-04 11:30:05</td>
        <td>Menunggu Konfirmasi Restoran</td>
        <td><button type="button" class="btn btn-primary">Detail</button>
        </td>
      </tr>
    </tbody>
  </table>

trigger_4/templates/ringkasan_pesanan.html
{% extends 'base.html' %}
<html>
{% block meta %}

<style>

    div {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

</style>

{% endblock meta %}

{% block content %}

<div class="row">
    <div class="col">
        <h2 class=" pt-4 pb-3"><strong>Ringkasan Pesanan</strong></h2>
    </div>
</div>

<div class="row">
    <div class="col">
        
        <div class="card my-4 shadow">
        <div class="card-body border-dark" style="width: 500px;">

        <div class="pb-3 pt-2 d-flex justify-content-center">
            <p class=" pt-2">Waktu Pemesanan: 2022-11-04 11:30:05</p>
        </div>

        <div class="pb-3 pt-2 d-flex justify-content-center">
            <p class=" pt-2">Nama Pelanggan: Mikayla Putri</p>
            <p class=" pt-2">Jalan: Jalan Bahagia nomor 72</p>
            <p class=" pt-2">Kecamatan: Cinere</p>
            <p class=" pt-2">Kota: Depok</p>
            <p class=" pt-2">Provinsi: Jawa Barat</p>
        </div>

        <div class="pb-3 pt-2 d-flex justify-content-center">
            <p class=" pt-2">Restoran: Warung Mantap Depok</p>
            <p class=" pt-2">Jalan: Jalan Sejahtera nomor 5</p>
            <p class=" pt-2">Kecamatan: Bojongsari</p>
            <p class=" pt-2">Kota: Depok</p>
            <p class=" pt-2">Provinsi: Jawa Barat</p>
        </div>

        <div class="pb-3 pt-2 d-flex justify-content-center">
            <p class=" pt-2">Makanan yang dipesan:</p>
            <p class=" pt-2">- Ayam Goreng (1)</p>
            <p class=" pt-2">- Ice Cream (2)</p>
            <p class=" pt-2">Total Harga Makanan: 11000</p>
            <p class=" pt-2">Total Diskon: 0</p>
            <p class=" pt-2">Biaya Pengantaran: 4000</p>
            <p class=" pt-2">Total Biaya: 15000</p>
            <p class=" pt-2">Jenis Pembayaran: Restopay</p>
        </div>

        <div class="pb-3 pt-2 d-flex justify-content-center">
            <p class=" pt-2">Status Pembayaran: Berhasil</p>
            <p class=" pt-2">Status Pesanan: Menunggu Konfirmasi Restoran</p>
        </div>

        <div class="pb-3 pt-2 d-flex justify-content-center">
            <p class=" pt-2">Kurir: -</p>
            <p class=" pt-2">Plat Kendaraan: -</p>
            <p class=" pt-2">Jenis Kendaraan: -</p>
            <p class=" pt-2">Merk Kendaraan: -</p>
        </div>

        <div><button type="button" class="btn btn-primary">Kembali</button></div>
    </div>
</div>
</html>
{% endblock content %}

trigger_4/templates/tpel_alamat_form.html
{% extends 'base.html' %}

{% block meta %}

{% endblock meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% block content %}

{% include 'navbar_pelanggan.html' %}
<div class="d-flex flex-row justify-content-center">
    <div class="d-flex flex-column align-items-center"> 
        <form id="form-tpel-alamat" method="POST">
            {% csrf_token %}
            <h2 class="lead pt-4 pb-3">FORM PENGISIAN ALAMAT PEMESANAN MAKANAN</h1>
            
            <!-- cards -->
            <div class="card d-flex flex-column align-items-center p-2" style="width: 900px;">
                
                <div class="d-flex flex-row py-1">
                </div>
                <div class="d-flex flex-row justify-content-between px-2 py-1 align-items-center" style="width: 100%;"> 
                    <label for="street" class="fs-6 text-wrap fw-normal" style="width: 60%;">Jalan</label>
                    <input type="text" id="street" name="street" placeholder="Jalan" class="form-control" style="width: 40%;" required>
                </div>
                <div class="d-flex flex-row justify-content-between px-2 py-1 align-items-center" style="width: 100%;"> 
                    <label for="district" class="fs-6 text-wrap fw-normal" style="width: 60%;">Kecamatan</label>
                    <input type="text" id="district" name="district" placeholder="Kecamatan" class="form-control" style="width: 40%;" required>
                </div>
                <div class="d-flex flex-row justify-content-between px-2 py-1 align-items-center" style="width: 100%;"> 
                    <label for="city" class="fs-6 text-wrap fw-normal" style="width: 60%;">Kota</label>
                    <input type="text" id="city" name="city" placeholder="Kota" class="form-control" style="width: 40%;" required>
                </div>
                <div class="d-flex flex-row justify-content-between px-2 py-1 align-items-center" style="width: 100%;"> 
                    <label for="province" class="fs-6 text-wrap fw-normal" style="width: 60%;">Provinsi</label>
                    <select id="province" name="province" placeholder="Provinsi" class="form-control" style="width: 40%;" required>
                        {% for p in province_list %}
                        <option>{{ p.province }}</option>
                        {% endfor %}     
                    </select>
                </div>
                <div class="d-flex flex-row py-1">
                </div>
            </div>
            
            <div class="pt-3"></div>
            <button type="submit" class="btn btn-sm btn-primary" style="width: 20%;">Lanjut</button>
            
        </form>
    </div>
</div>

{% endblock content %}

trigger_4/templates/tpel_choose_restolist_form.html
{% extends 'base.html' %}

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}

{% block content %}

{% include 'navbar_pelanggan.html' %}
<div class="d-flex flex-row justify-content-center ">
    <div class="d-flex flex-column align-items-center">
        
        <h2 class="lead pt-4 pb-3">PILIHAN RESTORAN</h1>
        
        <!-- cards -->
        <div class="card" style="width: 900px;">

            <div class="px-2 py-3 border-dark d-flex flex-row align-items-center" style="width: 100%;">
              <div class="d-flex flex-column align-items-center px-2 fs-6 text-wrap fw-normal" 
              style="width: 5%;">No</div>
              
              <div class="d-flex flex-column align-items-start px-2 fs-6 text-wrap fw-normal" 
              style="width: 35%;">Nama Restoran, Cabang</div>

              <div class="d-flex flex-column align-items-start px-2 fs-6 text-wrap fw-normal" 
              style="width: 35%;">Promo Berlangsung</div>
              
              <div class="d-flex flex-column align-items-start px-2 fs-6 text-wrap fw-normal" 
              style="width: 20%;">Aksi</div>
            </div>

            
            {% for r in restaurant_list %}
            <div class="px-2 border-dark d-flex flex-column align-items-center" style="width: 100%;">
              <div class="d-flex flex-row align-items-center" style="width: 100%;">
                
                <!-- No -->
                <div class="d-flex flex-column align-items-end px-2 fs-6 text-wrap fw-normal" 
                style="width: 5%;">{{ forloop.counter }}</div>
                <!-- Nama Restoran, Cabang -->
                <div class="d-flex flex-column align-items-start px-2 fs-6 text-wrap fw-normal gap-1" 
                style="width: 35%;">
                  <div id="rname" name="rname" class="text-wrap fw-bold">{{ r.rname }}</div>
                  <div id="rbranch" name="rbranch" class="text-wrap fw-semibold text-secondary">{{ r.rbranch }}</div>
                </div>
                <!-- Promo Berlangsung -->
                <div class="d-flex flex-column align-items-start px-2 fs-6 text-wrap fw-normal" 
                style="width: 35%;">
                  {% for p in promo_list %}
                    {% if r.rname == p.rname %}
                    <div class="text-wrap fw-semibold">{{ p.promoname }}</div>
                    {% endif %}
                  {% endfor %}
                </div>
                <!-- Aksi -->
                <a href="../../list-menu/{{ r.rname }}/{{ r.rbranch }}/" type="submit" class="btn btn-sm btn-primary" style="width: 20%;">Pilih</a>
              </div>
              <div class="pt-3"></div>
            </div>
            <div class="d-flex flex-row py-1">
            </div>
            {% endfor %}
            
        </div>

    </div>
</div>

{% endblock content %}