sirest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger_2/', include('trigger_2.urls')),
    path('trigger_3/', include('trigger_3.urls')),
    path('trigger-5/', include('trigger_5.urls')),
    path('trigger_6/', include('trigger_6.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('trigger-4/', include('trigger_4.urls')),
    path('login_page/', include('login_page.urls')),
]

trigger_3/urls.py
from django.urls import path
from . import views

app_name = 'trigger_3'

urlpatterns = [
    path('makanan_add/', views.tambah_makanan, name='halaman_tambah_makanan'),
    path('makanan_update/', views.update_makanan, name='halaman_update_makanan'),
    path('makanan/', views.makanan_page, name='halaman_makanan'),
    path('hapus_makanan/<str:rname>/<str:rbranch>/<str:foodname>/', views.delete_makanan, name='delete_makanan'),
    path('restoran_makanan_detail/', views.restoran_detail_makanan, name='halaman_detail_makanan_restoran'),
    path('restoran_makanan_menu/', views.restoran_menu_makanan, name='halaman_menu_makanan_restoran'),
    path('restoran_makanan/', views.restoran_makanan_page, name='halaman_makanan_restoran'),
    path('tarif_pengiriman_add/', views.tambah_tarif_pengiriman, name='halaman_tambah_tarif_pengiriman'),
    path('tarif_pengiriman_update/', views.update_tarif_pengiriman, name='halaman_update_tarif_pengiriman'),
    path('hapus_tarif_pengiriman/<str:id>/', views.delete_tarif_pengiriman, name='delete_tarif_pengiriman'),
    path('tarif_pengiriman/', views.tarif_pengiriman_page, name='halaman_tarif_pengiriman'),
]

trigger_3/views.py
from django.shortcuts import render, redirect
from sirest.utils import *
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from sirest.utils import get_role, is_authenticated
from django.db import connection
from django.urls import reverse

# Create your views here.
def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def tambah_makanan(request):
    return render(request, 'makanan_add.html')

def update_makanan(request):
    return render(request, 'makanan_update.html')

def makanan_page(request):
    # if is_authenticated(request) == True:
    #     cursor = connection.cursor()
    #     cursor.execute()
    # else:
    #     response = HttpResponseRedirect(reverse("login_page:login"))
    #     return response
    cursor = connection.cursor()
    cursor.execute("SET SEARCH_PATH TO SIREST")
    cursor.execute('SELECT * FROM FOOD INNER JOIN FOOD_CATEGORY ON FOOD.FCATEGORY = FOOD_CATEGORY.id')
    hasil = namedtuplefetchall(cursor)
    return render(request, 'makanan.html', {'hasil':hasil})

def delete_makanan(request, rname, rbranch, foodname): 
    get_query(f"""
        DELETE FROM sirest.FOOD 
        WHERE rname = '{rname}' AND rbranch = '{rbranch}' AND foodname = '{foodname}';
    """)
    return redirect('/trigger_3/makanan/')

def restoran_detail_makanan(request):
    return render(request, 'restoran_makanan_detail.html')

def restoran_menu_makanan(request):
    return render(request, 'restoran_makanan_menu.html')

def restoran_makanan_page(request):
    return render(request, 'restoran_makanan.html')

def tarif_pengiriman_page(request):
    cursor = connection.cursor()
    cursor.execute("SET SEARCH_PATH TO SIREST")
    cursor.execute('SELECT * FROM DELIVERY_FEE_PER_KM')
    hasil = namedtuplefetchall(cursor)
    return render(request, 'tarif_pengiriman.html', {'hasil':hasil})

def tambah_tarif_pengiriman(request):
    return render(request, 'tarif_pengiriman_add.html')

def update_tarif_pengiriman(request):
    return render(request, 'tarif_pengiriman_update.html')

def delete_tarif_pengiriman(request, id): 
    get_query(f"""
        DELETE FROM sirest.DELIVERY_FEE_PER_KM 
        WHERE id = '{id}';  
    """)

    return redirect('/trigger_3/tarif_pengiriman/')

trigger_3/templates/makanan.html
{% extends 'base.html' %}
{% block meta %}
  <!-- Progress bar loading -->
  <script src="../assets/frontend/vendor/pace/pace.min.js"></script>
  <link rel="stylesheet" href="../assets/frontend/vendor/pace/pace.css">
  <link rel="stylesheet" href="https://unpkg.com/placeholder-loading/dist/css/placeholder-loading.min.css">

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Nyat Server Control">
  <meta name="author" content="">
  <!-- Custom fonts -->
  <link href="../assets/frontend/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <!-- Bootstrap styles -->
  <link href="../assets/frontend/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- NOTE: ALL SCRIPT MOVE HERE FROM BOTTOM -->

  <!-- Bootstrap core JavaScript-->
  <script src="../assets/frontend/vendor/jquery/jquery.min.js"></script>
  <script src="../assets/frontend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- Core plugin JavaScript-->
  <script src="../assets/frontend/vendor/jquery-easing/jquery.easing.min.js"></script>
  <!-- Custom styles for ALL page-->
  <link href="../assets/frontend/css/index.css" rel="stylesheet">
  <!-- Custom styles for data tables page -->
  <link href="../assets/frontend/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
  <link href="../assets/frontend/vendor/datatables/responsive.bootstrap4.min.css" rel="stylesheet">
  <!-- Page data tables level plugins -->
  <script src="../assets/frontend/vendor/datatables/jquery.dataTables.min.js"></script>
  <script src="../assets/frontend/vendor/datatables/dataTables.bootstrap4.min.js"></script>
  <script src="../assets/frontend/vendor/datatables/dataTables.responsive.min.js"></script>
  <script src="../assets/frontend/vendor/datatables/responsive.bootstrap4.min.js"></script>
{% endblock meta %}

{% block content %}
<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column bg-white overflow-hidden">

      <!-- Main Content -->
      <div id="content">

    <!-- Topbar
    <nav class="navbar navbar-expand-lg navbar-light bg-white topbar h-auto container shadow-sm fixed-top">
		  <div class="">
		    <a class="navbar-brand d-flex mr-auto text-primary" href="../index.html">
		      <span class="font-weight-bold mx-1">
		        <i class="fas fa-utensils"></i> SIREST
		      </span>
		    </a>
		  </div>

		  <div class="topbar-divider d-none d-lg-block"></div>

		  <div class="navbar-text">
		    <button class="btn btn-link btn-sm d-lg-none rounded-circle" type="button" data-toggle="collapse" data-target="#navToggler1" aria-controls="navToggler1" aria-expanded="false" aria-label="Toggle navigation">
		      <i class="fa fa-bars"></i>
		    </button>
      </div>

		  <div class="collapse navbar-collapse" id="navToggler1">
		    <hr class="d-lg-none m-0">
		    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item p-1 p-lg-0 dropdown">
		        <a class="btn btn-link text-decoration-none mr-1 btn-sm dropdown-toggle" href="#" id="menu_about" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          <i class="fas fa-sliders-h"></i> Makanan
		        </a>
		        <div class="dropdown-menu keep-open dropdown-menu-right animated--grow-in shadow-sm ml-2 ml-lg-0" aria-labelledby="menu_about">
              <h6 class="dropdown-header">Manajemen Data</h6>
		          <a class="dropdown-item" href="makanan_add.html"><i class="fas fa-plus"></i> Buat Makanan</a>
		          <a class="dropdown-item" href="makanan.html"><i class="fas fa-eye"></i> Daftar Makanan</a>
		        </div>
		      </li>
          <li class="nav-item p-1 p-lg-0 dropdown">
		        <a class="btn btn-link text-decoration-none mr-1 btn-sm dropdown-toggle" href="#" id="menu_about" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          <i class="fas fa-sliders-h"></i> Restoran
		        </a>
		        <div class="dropdown-menu keep-open dropdown-menu-right animated--grow-in shadow-sm ml-2 ml-lg-0" aria-labelledby="menu_about">
              <h6 class="dropdown-header">Manajemen Data</h6>
		          <a class="dropdown-item" href="restoran_makanan.html"><i class="fas fa-eye"></i> Daftar Restoran dan Makanan</a>
		        </div>
		      </li>
          <li class="nav-item p-1 p-lg-0 dropdown">
		        <a class="btn btn-link text-decoration-none mr-1 btn-sm dropdown-toggle" href="#" id="menu_about" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          <i class="fas fa-sliders-h"></i> Manajemen Data
		        </a>
		        <div class="dropdown-menu keep-open dropdown-menu-right animated--grow-in shadow-sm ml-2 ml-lg-0" aria-labelledby="menu_about">
              <h6 class="dropdown-header">Manajemen Data</h6>
		          <a class="dropdown-item" href="tarif_pengiriman.html"><i class="fas fa-users"></i> Tarif Pengiriman</a>
		          <a class="dropdown-item" href="makanan.html"><i class="fas fa-users"></i> Makanan</a>
		          <a class="dropdown-item" href="kategori_makanan.html"><i class="fas fa-users"></i> Kategori Makanan</a>
		          <a class="dropdown-item" href="transaksi_pesanan.html"><i class="fas fa-users"></i> Transaksi Pesanan</a>

              <div class="dropdown-divider"></div>
              
              <h6 class="dropdown-header">Manajemen Contoh</h6>
              <a class="dropdown-item" href="#"><i class="fas fa-user"></i> Lorem Ipsum</a>
		        </div>
		      </li>
		      <li class="nav-item p-1 p-lg-0">
		        <a href="../index.html" class="">
		          <button class="btn btn-link text-decoration-none mr-1 btn-sm" type="button">
		            <i class="fas fa-sign-out-alt"></i> Logout
		          </button>
		        </a>
		      </li>
		    </ul>
		  </div>

		</nav>

    <!-- End of Topbar -->
    {% if role == 'Pelanggan' %}
    {% include 'navbar_pelanggan.html' %}

    {% elif role == 'Restoran' %}
    {% include 'navbar_restoran.html' %}

    {% elif role == 'Kurir' %}
    {% include 'navbar_kurir.html' %}

    {% endif %}

    <div id="main_content">
      <section id="secHeader" class="row h-75 my-3 my-md-0">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12 my-md-1 text-center">
              <h1 class="h3 text-gray-800 font-weight-bold">Makanan</h1>
              <hr>
            </div>
            <div class="col-12">
              <a href="makanan_add.html" class="mb-2 btn btn-primary btn-sm">Tambah Data</a>
              <a href="restoran_makanan.html" class="mb-2 btn btn-primary btn-sm">Daftar Restoran dan Makanan</a>
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Makanan</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered dt-responsive" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama Makanan</th>
                                    <th>Deskripsi</th>
                                    <th>Stok</th>
                                    <th>Harga</th>
                                    <th>Kategori Makanan</th>
                                    <th>Bahan Makanan</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                              {% for i in hasil %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ i.foodname }}</td>
                                    <td>{{ i.description }}</td>
                                    <td>{{ i.stock }}</td>
                                    <td>{{ i.price }}</td>
                                    <td>{{ i.name }}</td>
                                    <td>{{ i.description }}</td>
                                    <td>
                                      <a href="makanan_update.html" class="btn btn-info btn-sm">Ubah</a>
                                      <a href="{% url 'trigger_3:delete_makanan' rname=i.rname rbranch=i.rbranch foodname=i.foodname %}" class="btn btn-danger btn-sm">Hapus</a>
                                    </td>
                                </tr>
                              {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white shadow-lg py-3">
        <div class="container my-auto">
          <div class="text-center my-auto">
            <small>&copy; SIREST 2022
            </small>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- NOTE: ALL SCRIPT FOR THIS PAGE -->
  <script src="../assets/frontend/js/datatables.js"></script>
  <script src="../assets/frontend/js/index.js"></script>

</body>
{% endblock content %}

trigger_3/templates/tarif_pengiriman.html
{% extends 'base.html' %}
{% block meta %}
  <!-- Progress bar loading -->
  <script src="../assets/frontend/vendor/pace/pace.min.js"></script>
  <link rel="stylesheet" href="../assets/frontend/vendor/pace/pace.css">
  <link rel="stylesheet" href="https://unpkg.com/placeholder-loading/dist/css/placeholder-loading.min.css">

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Nyat Server Control">
  <meta name="author" content="">
  <!-- Custom fonts -->
  <link href="../assets/frontend/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <!-- Bootstrap styles -->
  <link href="../assets/frontend/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <!-- NOTE: ALL SCRIPT MOVE HERE FROM BOTTOM -->

  <!-- Bootstrap core JavaScript-->
  <script src="../assets/frontend/vendor/jquery/jquery.min.js"></script>
  <script src="../assets/frontend/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- Core plugin JavaScript-->
  <script src="../assets/frontend/vendor/jquery-easing/jquery.easing.min.js"></script>
  <!-- Custom styles for ALL page-->
  <link href="../assets/frontend/css/index.css" rel="stylesheet">
  <!-- Custom styles for data tables page -->
  <link href="../assets/frontend/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
  <link href="../assets/frontend/vendor/datatables/responsive.bootstrap4.min.css" rel="stylesheet">
  <!-- Page data tables level plugins -->
  <script src="../assets/frontend/vendor/datatables/jquery.dataTables.min.js"></script>
  <script src="../assets/frontend/vendor/datatables/dataTables.bootstrap4.min.js"></script>
  <script src="../assets/frontend/vendor/datatables/dataTables.responsive.min.js"></script>
  <script src="../assets/frontend/vendor/datatables/responsive.bootstrap4.min.js"></script>
{% endblock meta %}

{% block content %}
<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column bg-white overflow-hidden">

      <!-- Main Content -->
      <div id="content">

    <!-- Topbar
    <nav class="navbar navbar-expand-lg navbar-light bg-white topbar h-auto container shadow-sm fixed-top">
		  <div class="">
		    <a class="navbar-brand d-flex mr-auto text-primary" href="../index.html">
		      <span class="font-weight-bold mx-1">
		        <i class="fas fa-utensils"></i> SIREST
		      </span>
		    </a>
		  </div>

		  <div class="topbar-divider d-none d-lg-block"></div>

		  <div class="navbar-text">
		    <button class="btn btn-link btn-sm d-lg-none rounded-circle" type="button" data-toggle="collapse" data-target="#navToggler1" aria-controls="navToggler1" aria-expanded="false" aria-label="Toggle navigation">
		      <i class="fa fa-bars"></i>
		    </button>
      </div>

		  <div class="collapse navbar-collapse" id="navToggler1">
		    <hr class="d-lg-none m-0">
		    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item p-1 p-lg-0 dropdown">
		        <a class="btn btn-link text-decoration-none mr-1 btn-sm dropdown-toggle" href="#" id="menu_about" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          <i class="fas fa-sliders-h"></i> Pesanan
		        </a>
		        <div class="dropdown-menu keep-open dropdown-menu-right animated--grow-in shadow-sm ml-2 ml-lg-0" aria-labelledby="menu_about">
              <h6 class="dropdown-header">Manajemen Data</h6>
		          <a class="dropdown-item" href="tarif_pengiriman_add.html"><i class="fas fa-plus"></i> Buat Tarif Pengiriman per KM</a>
		          <a class="dropdown-item" href="tarif_pengiriman.html"><i class="fas fa-eye"></i> Daftar Tarif Pengiriman per KM</a>
		        </div>
		      </li>
          <li class="nav-item p-1 p-lg-0 dropdown">
		        <a class="btn btn-link text-decoration-none mr-1 btn-sm dropdown-toggle" href="#" id="menu_about" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          <i class="fas fa-sliders-h"></i> Manajemen Data
		        </a>
		        <div class="dropdown-menu keep-open dropdown-menu-right animated--grow-in shadow-sm ml-2 ml-lg-0" aria-labelledby="menu_about">
              <h6 class="dropdown-header">Manajemen Data</h6>
		          <a class="dropdown-item" href="tarif_pengiriman.html"><i class="fas fa-users"></i> Tarif Pengiriman</a>
		          <a class="dropdown-item" href="makanan.html"><i class="fas fa-users"></i> Makanan</a>
		          <a class="dropdown-item" href="kategori_makanan.html"><i class="fas fa-users"></i> Kategori Makanan</a>
		          <a class="dropdown-item" href="transaksi_pesanan.html"><i class="fas fa-users"></i> Transaksi Pesanan</a>

              <div class="dropdown-divider"></div>
              
              <h6 class="dropdown-header">Manajemen Contoh</h6>
              <a class="dropdown-item" href="#"><i class="fas fa-user"></i> Lorem Ipsum</a>
		        </div>
		      </li>
		      <li class="nav-item p-1 p-lg-0">
		        <a href="../index.html" class="">
		          <button class="btn btn-link text-decoration-none mr-1 btn-sm" type="button">
		            <i class="fas fa-sign-out-alt"></i> Logout
		          </button>
		        </a>
		      </li>
		    </ul>
		  </div>

		</nav>

    <!-- End of Topbar -->

    {% include 'navbar_admin.html' %}

    <div id="main_content">
      <section id="secHeader" class="row h-75 my-3 my-md-0">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-12 my-md-1 text-center">
              <h1 class="h3 text-gray-800 font-weight-bold">Tarif Pengiriman per KM</h1>
              <hr>
            </div>
            <div class="col-12">
              <a href="tarif_pengiriman_add.html" class="mb-2 btn btn-primary btn-sm">Tambah Data</a>
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Tarif Pengiriman</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered dt-responsive" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Provinsi</th>
                                    <th>Biaya Motor</th>
                                    <th>Biaya Mobil</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                              {% for i in hasil %}
                              <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{ i.province }}</td>
                                <td>{{ i.MotorFee }}</td>
                                <td>{{ i.MobilFee }}</td>
                                <td>
                                  <a href="tarif_pengiriman_update.html" class="btn btn-info btn-sm">Ubah</a>
                                  <a href="{% url 'trigger_3:delete_tarif_pengiriman' id=i.id %}" class="btn btn-danger btn-sm">Hapus</a>
                                </td>
                              </tr>
                              {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white shadow-lg py-3">
        <div class="container my-auto">
          <div class="text-center my-auto">
            <small>&copy; SIREST 2022
            </small>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- NOTE: ALL SCRIPT FOR THIS PAGE -->
  <script src="../assets/frontend/js/datatables.js"></script>
  <script src="../assets/frontend/js/index.js"></script>

</body>
{% endblock content %}